# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore & Build
      run: |
        $DockerPullJob = Start-Job { docker pull mcr.microsoft.com/azure-sql-edge:1.0.7 }
        dotnet restore
        dotnet build --no-restore --configuration Release
        while($DockerPullJob.State -eq "Running")
        {
          Write-Host "pulling docker image..."
          Start-Sleep -Seconds 1
        }
      shell: pwsh
    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release
